artifacts:
  artifacts_dir: artifacts
  pickle_format_data_dir: pickle_format_data
  img_pickle_file_name: img_pickle_file.pkl
  features_extraction_dir: extracted_features
  extracted_features_name: embeddings.pkl
  upload_image_dir: uploads
